services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tripvar-web
    ports:
      - "8000:8000"
      - "9929:9929"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - GATSBY_TELEMETRY_DISABLED=1
      - GATSBY_HUGGINGFACE_API_KEY=${GATSBY_HUGGINGFACE_API_KEY}
    tty: true
    stdin_open: true

  prod:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: tripvar-prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - GATSBY_HUGGINGFACE_API_KEY=${GATSBY_HUGGINGFACE_API_KEY}
    depends_on:
      - web 